global using Mapster;
global using Microsoft.AspNetCore.Mvc;
global using OutbornE_commerce.BAL.Dto;
global using OutbornE_commerce.BAL.Dto.Cities;
global using OutbornE_commerce.BAL.Dto.Countries;
global using OutbornE_commerce.BAL.Repositories.Cities;
global using OutbornE_commerce.BAL.Repositories.Countries;
global using OutbornE_commerce.DAL.Enums;
global using OutbornE_commerce.DAL.Models;